# Generated by Django 6.0 on 2026-02-13 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrower',
            name='national_id_image',
            field=models.ImageField(blank=True, null=True, upload_to='national_ids/'),
        ),
        migrations.AddField(
            model_name='borrower',
            name='residence_map_image',
            field=models.ImageField(blank=True, null=True, upload_to='residence_maps/'),
        ),
    ]
