# Generated by Django 6.0 on 2026-02-15 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_loan_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='paid_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
